### ISSUE TITLE
Add information in thread to documentation

### ISSUE THREAD

**Issue by eugeneburger** [NOAA-PMEL/PyFerret#108]
Add information on the restriction described here to the documentation

https://www.pmel.noaa.gov/maillists/tmap/ferret_users/fu_2019/msg01105.html

**Comment by ACManke** [comment]
See  also issue #51  where comments include example code

**Comment by josborne-noaa** [comment]
I've updated the documentation with the work-around as Karl wrote it in #51 as an example here under /PLOT/GRATICULE: https://ferret.lark.pmel.noaa.gov/documentation/users-guide/commands-reference/PLOT
