### ISSUE TITLE
Installation through conda in Mac M1 is freezing at solving environment

### ISSUE THREAD

**Issue by VRThallam** [NOAA-PMEL/PyFerret#144]
Hi,
My installation through conda in Mac M1 is freezing in the solving environment. Please have a look at the attachment. 
<img width="1413" alt="Screenshot 2024-11-05 at 15 43 29" src="https://github.com/user-attachments/assets/1aa766b2-1aa6-4621-9104-d99946497243">

**Comment by venugopalrt** [comment]
I could solve the issue by clearing the old cache and reinstalling the conda.
