### ISSUE TITLE
ferretmagic.py to be removed from distribution

### ISSUE THREAD

**Issue by PBrockmann** [NOAA-PMEL/PyFerret#30]
I have packaged ferretmagic as a module and fix some changes needed by ipython 5.1.0
Installation is now possible from pip
```pip install ferretmagic```

See https://pypi.python.org/pypi/ferretmagic/2016.10

ferretmagic.py should be removed from the pyferret distribution otherwise you pick the old one.

**Comment by karlmsmith** [comment]
Excellent; thank you Patrick.
ferretmagic.py removed from PyFerret source and future distributions.  README.md updated to provide information on getting the latest ferretmagic.py
