### ISSUE TITLE
Add new spectrum files to palettes directory

### ISSUE THREAD

**Issue by PBrockmann** [NOAA-PMEL/PyFerret#31]
New palettes prepared from matplotlib (especially 'viridis', 'inferno', 'plasma', 'magma') could be added to pyferret distribution.

Read the thread from http://www.pmel.noaa.gov/maillists/tmap/ferret_users/fu_2015/msg00474.html
The tar ball is available from: http://www.pmel.noaa.gov/maillists/tmap/ferret_users/fu_2015/msg00475.html

**Comment by karlmsmith** [comment]
From Ansley:

We had added these back in Nov 2015, using these palette files that Patrick sent and which are in the latest Ferret distribution:
 ```
> Fpalette mpl
 * * * * * * * * in /home/users/tmap/ferret/rhel6-x86_64-linux/ppl
 mpl_PSU_inferno.spk:
 mpl_PSU_magma.spk:
 mpl_PSU_plasma.spk:
 mpl_PSU_viridis.spk:
```
I have added copies of these under the simpler names viridis, inferno, plasma, magma.

Added to both Ferret and PyFerret.
