### ISSUE TITLE
Conda install issue

### ISSUE THREAD

**Issue by eugeneburger** [NOAA-PMEL/PyFerret#32]
I separately ran the `conda install` command for the pixman library. Anaconda then update pixman to this pixman 0.32.6-0

Running pyferret I got the regular dylib error with libpixman:
`anaconda2/envs/FERRET/lib//libpixman-1.0.dylib: malformed mach-o image: load command #13 length (0) too small in /Users/burger/anaconda2/envs/FERRET/lib//libpixman-1.0.dylib`

I then tried running the `conda update pixman` command **after** running `source activate FERRET`. This time in installed pixman 0.34.0 fron conda forge, and this time pyferret ran without any issue.

Maybe add this to the documentation?

**Comment by ocefpaf** [comment]
I should pin pixman to ensure that step isn't necessary. I will do that
soon. (I am away until Dec 3rd)

**Comment by ocefpaf** [comment]
PR https://github.com/conda-forge/pyferret-feedstock/pull/22 should solved this. (Note that I cannot close an issue here and ultimately this is a conda packaging issue and not a `pyferret` issue.)
