### ISSUE TITLE
macOS requirements

### ISSUE THREAD

**Issue by kieloben** [NOAA-PMEL/PyFerret#36]
Dear pyFerreter,

just downloaded PyFerret v7.0.0 for macOS Sierra, but couldn't get it running. Tried to download the required packages with Macports, which was easy for easy for numpy and scipy but failed to identify libpangocairo and others. And that's were it failed in the end

Could you please provide a recipe how to get pyFerret running on a fresh macOS Sierra using a Macports (or any other package installer)? The requirements given for Ubuntu don't really help.

Thanks and kind regards,
Arne

**Comment by karlmsmith** [comment]
Hi Arne,

There is a file README_pyferret_mac_homebrew that discusses how to build it using homebrew to add the required packages.  Homebrew now has been updated to build, if needed, and install python3 and pyqt5 so those notes are a little bit out-of-date.

However, there is still the issue with Mac OS Sierra not being able to display plots - see issue #33.  I am able to build PyFerret for the previous Mac OS version (using python3 and pyqt5) and is works fine, but the exact same build on Sierra does not.

Karl

**Comment by kieloben** [comment]
Thanks, Karl. That worked.

Please note that also for the rebuild PyFerret package, I had to install cairo and pango.

PyFerret v7 now starts, however creates not output rather going through the -nodisplay option. But I guess, this is a reported issue and I shall wait for a new release.

Best wishes, Arne 


> Am 23.02.2017 um 22:07 schrieb Karl M. Smith - NOAA <notifications@github.com>:
> 
> Hi Arne,
> 
> There is a file README_pyferret_mac_homebrew that discusses how to build it using homebrew to add the required packages. Homebrew now has been updated to build, if needed, and install python3 and pyqt5 so those notes are a little bit out-of-date.
> 
> However, there is still the issue with Mac OS Sierra not being able to display plots - see issue #33. I am able to build PyFerret for the previous Mac OS version (using python3 and pyqt5) and is works fine, but the exact same build on Sierra does not.
> 
> Karl
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Dr. Arne Biastoch  .  biastoch@biastoch.de
Am Tannenberg 65  
D-24106 Kiel

fon: ++49 (0)431 305 2784
fax: ++49 (0)431 305 2785
