### ISSUE TITLE
Ferret ($labnum_datitl) not defined in PyFerret

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/PyFerret#53]
Try to use the SOCAT preview plot scripts with PyFerret gives the following error on many of the scripts.  However, these work fine with Ferret.  I am guessing ($labnum_datitl) is autodefined in Ferret but not PyFerret.
```
  let labttl = ($labnum_datitl)
 !-> DEFINE VARIABLE labttl =
 **ERROR: command syntax: LABTTL = ???
````

**Comment by karlmsmith** [comment]
@AnsleyManke - FYI

**Comment by karlmsmith** [comment]
In Ferret:
```
yes? use coads_climatology
yes? shade /l=5 sst
yes? say ($labnum_datitl)
 !-> MESSAGE/CONTINUE 3
3
```
but in PyFerret:
```
yes? use coads_climatology
yes? shade /l=5 sst
yes? say ($labnum_datitl)
 !-> MESSAGE/CONTINUE

```
Change between Hershey and non-Hershey fonts make no difference.

**Comment by AnsleyManke** [comment]
Closing this - I'll make a new Ferret ticket.
