### ISSUE TITLE
**ERROR <class 'AttributeError'>: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by ryofurue** [NOAA-PMEL/PyFerret#66]
Hi,

I've installed pyferret (see below) on macOS Catalina .  When I tested it like

    yes? set data levitsu_climatology
    yes? plot/y=35N/z=0 temp

the following error is repeatedly displayed in an extremely rapid succession

    **ERROR <class 'AttributeError'>: module 'time' has no attribute 'clock'

I could do nothing but to kill pyferret from another terminal.

Perhaps this is a new issue on Catalina ?

Regards,
Ryo
-----
I had already had pyferret installed.  I started from the second line.

    [ $ brew cask install miniconda ]
    $ PATH="/usr/local/miniconda/bin:$PATH"
    $ conda update conda
    $ conda create --name FERRET
    $ source activate FERRET
    $ conda install -c conda-forge pyferret
    $ conda install -c conda-forge ferret_datasets

**Comment by karlmsmith** [comment]
Fixed in commit fff9bfc10ac8d7a2ddc60b310b68c686a1079dcc

**Comment by godderis** [comment]
Hello
I'm running pyferret on a new MacBook Pro Catalina. I got the same crash:
**ERROR <class 'AttributeError'>: module 'time' has no attribute 'clock'
I have python 3 installed, and anaconda 1.9.7

I have no idea how to solve that.

Thanks in advance

Yves

**Comment by karlmsmith** [comment]
Hi Yves,

On Thursday (14 Nov) I updated the conda build of PyFerret v7.5.0 to patch the Python code to resolve this problem.   If you update your pyferret package (to v7.5.0 build number 8), it should remove this error that arises in Python 3.8, as well as the issues PyFerret was having with Qt.  So something like:
```
conda update --all
conda update -n FERRET --all
```
(or using whatever conda environment name you used instead of `FERRET`)
should include the update of pyferret something like:
```
  pyferret                             7.5.0-py38h6780845_7 --> 7.5.0-py38h6780845_8
```

**Comment by ryofurue** [comment]
Thank you for the update!

However, after the commands you listed, I got this:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/Caskroom/miniconda/base/envs/FERRET/lib/python3.8/site- 
   packages/pyferret/__init__.py", line 45, in <module>
        from pyferret import libpyferret
    ImportError: dlopen(/usr/local/Caskroom/miniconda/base/envs/FERRET/lib/python3.8/site-packages/pyferret/libpyferret.cpython-38-darwin.so, 2): Library not loaded: @rpath/libfreetype.6.dylib
      Referenced from: /usr/local/Caskroom/miniconda/base/envs/FERRET/lib/python3.8/site-packages/pyferret/libpyferret.cpython-38-darwin.so
      Reason: Incompatible library version: libpyferret.cpython-38-darwin.so requires version 24.0.0 or later, but libfreetype.6.dylib provides version 23.0.0

So, I started over:

    conda update conda
    conda create --name FERRET
    source activate FERRET
    conda install -c conda-forge pyferret
    conda install -c conda-forge ferret_datasets

and pyferret finally worked!

Note that `conda create` asks whether to remove the existing FERRET env.  I said "yes" to that.  Perhaps that solved the problem (whatever it was).

**Comment by godderis** [comment]
This works !! Thanks a lot to both of you !
At the end, I had to re-install PyFerret, and everything is now working perfectly.

conda create -n FERRET -c conda-forge pyferret ferret_datasets --yes

Have a great day.

**Comment by ryofurue** [comment]
@godderis: Thank you for the useful information.  That means, a fresh-install script would consist of just these three lines:

    conda=/usr/local/miniconda/bin/conda  # or whatever appropriate
    $conda update --all
    $conda create -n FERRET -c conda-forge pyferret ferret_datasets --yes

**Comment by godderis** [comment]
Exactly.
